# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            PF 
tagline:          Swimming along ... 
url:              http://ponderingfish.github.io/
paginate:         1
baseurl:          /
author:
  name:           Pondering Fish 
  url:            
  email:          ponderingfish2014@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:          github.com/ponderingfish/ponderingfish.github.io 


pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
