# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pondering Fish 
tagline:          Swimming through life
url:              http://ponderingfish.github.io
paginate:         1
baseurl:          /
author:
  name:           Pondering Fish
  url:            https://twitter.com/
  email:          ponderingfish2014@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ponderingfish/ponderingfish.github.io 

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

excerpt_separator: <!--more-->  # you can specify your own separator, of course.
