# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            political tamasha
tagline:          navigating the Indian political circus

url:              http://mypages.iit.edu/~kvijayan/jekyll
paginate:         10
baseurl:          /
author:
  name:           krv
  url:            https://politicaltamasha.com/
  email:          krish.rao.v@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ponderingfish/ponderingfish.github.io 

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

gems:
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb
